background #131318
foreground #e4e1e9
cursor #e4e1e9
cursor_text_color #131318
selection_background #91909a
selection_foreground #e4e1e9
color0 #131318
color1 #ffb4ab
color2 #bec2ff
color3 #e7b9d5
color4 #c5c4dd
color5 #bec2ff
color6 #e7b9d5
color7 #e4e1e9
color8 #91909a
color9 #ffb4ab
color10 #bec2ff
color11 #e7b9d5
color12 #c5c4dd
color13 #bec2ff
color14 #91909a
color15 #e0e0ff
