background #0f1417
foreground #dee3e6
cursor #dee3e6
cursor_text_color #0f1417
selection_background #8a9296
selection_foreground #dee3e6
color0 #0f1417
color1 #ffb4ab
color2 #89d0ed
color3 #c4c3eb
color4 #b3cad5
color5 #89d0ed
color6 #c4c3eb
color7 #dee3e6
color8 #8a9296
color9 #ffb4ab
color10 #89d0ed
color11 #c4c3eb
color12 #b3cad5
color13 #89d0ed
color14 #8a9296
color15 #baeaff
