-- Generated by Ryoku Settings (Keybinds page); change it in the GUI, not here.
return {
	["SUPER + A"] = "CTRL + ALT + SHIFT + F",
	["SUPER + ALT + H"] = "SUPER + D",
	["SUPER + B"] = "SUPER + W",
	["SUPER + N"] = "SUPER + O",
	["SUPER + O"] = "SUPER + N",
	["SUPER + Return"] = "SUPER + Space",
	["SUPER + S"] = "SUPER + A",
	["SUPER + Space"] = "ALT + Space",
	["SUPER + W"] = "SUPER + B",
}
