-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  input = { kb_layout = "us", kb_variant = "", kb_options = "", follow_mouse = 1, natural_scroll = true, touchpad = { natural_scroll = true } },
})

hl.env("BROWSER", "zen-browser")

hl.window_rule({ name = "ryoku-user-1", match = { class = "kitty", title = "transparency" }, no_blur = true })
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("poweroff"))
hl.bind("CTRL + ALT + BackSpace", hl.dsp.exec_cmd("reboot"))
hl.bind("SUPER + S", hl.dsp.exec_cmd("./Execs/android-studio/bin/studio"))
